name: 🐛 Bug Report
description: Report an issue that should be fixed
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.

        Please try to include as much information as possible.
        Please answer the following questions for yourself before submitting an issue.

        - [ ] I am running the latest version
        - [ ] I checked the documentation and found no answer
        - [ ] I checked to make sure that this issue has not already been filed
  - type: input
    attributes:
      label: What version of `Edgeable` are you running?
      description: Copy the value from the command `docker exec edgeable version`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior?
      description: Please describe the behavior you are expecting.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior?
      description: What is the current behavior?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What are the steps required to reproduce the bug?
      description: Please provide detailed steps for reproducing the issue.
    validations:
      required: true